# Dependabot configuration version (mandatory at version 2)
version: 2

# Manage how updates are performed for each package manager
updates:
  # docker
  ## [ Dockerfile ]
  - package-ecosystem: "docker"
    directory: "/vendor/golang.org/x/net/http2"
    schedule:
      interval: "daily"

    reviewers:
      - "arqiva-tb/architects"
      - "arqiva-tb/developers"
      - "arqiva-tb/devops"
      - "arqiva-tb/ops"

    open-pull-requests-limit: 0 # no version updates

  # go
  ## [ go.mod ]
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers:
      - "arqiva-tb/architects"
      - "arqiva-tb/developers"
      - "arqiva-tb/devops"
      - "arqiva-tb/ops"

    open-pull-requests-limit: 0 # no version updates
